# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2acf4948e1604abe60631eccee66eb6fa5bfb53497979c88a60d4ee84e3046ccdced36a94c93c28f90a8d10cf705d1b92de77936642655b3862dd4d1b6630f0b

test:
  secret_key_base: a79090800bf20db6abc763af9497e980957b4e8526fd71e2b19fc4cb55dbcf655d19b2d113deea5aa35e59785311d1399cfd50365dc612f98a0bb6e41702d499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
